version: '3.8'
services:
  auto_buy_items:
    build: .
    container_name: auto_buy_items
    network_mode: host
    ipc: "host"
    environment:
      steamid: 1234567890
      shared_secret: /afdgfdgvbdfgZ4grdfTR4=
      identity_secret: DGFcvdfgPQERFOcdv=
      STEAM_API_KEY: DSVDS43534tMKGF4T4ERG
      STEAM_LOGIN: username
      STEAM_PASSOWORD: password123
      TELEGRAM_TOKEN: 1234567890:fdgGGDFSDGFDXGBDFBFDGFDGFDGDCb8
      TELEGRAM_CHAT_ID: 1234567890
      PROXY: 
      USERNAME_PROXY:
      PASSWORD_PROXY:
    restart: always